import React from 'react';
import { AlertCircle, CheckCircle2 } from 'lucide-react';

const ComparisonSection = () => {
  return (
    <section className="mx-auto max-w-7xl px-4 py-24 sm:px-6 lg:px-8">
      
      {/* Title */}
      <div className="text-center">
        <span className="rounded-full bg-neutral-100 px-3 py-1 text-xs font-semibold text-neutral-900 dark:bg-neutral-800 dark:text-neutral-100">
          Efficiency
        </span>
        <h2 className="mt-4 text-3xl font-extrabold tracking-tight text-neutral-900 dark:text-white sm:text-4xl">
          Why CortexCare?
        </h2>
        <p className="mx-auto mt-4 max-w-2xl text-base text-neutral-500 dark:text-neutral-400">
          Compare the documentation overhead of traditional workflows against the automated CortexCare model.
        </p>
      </div>

      {/* Side-by-Side Comparison */}
      <div className="mt-16 grid grid-cols-1 gap-8 md:grid-cols-2">
        
        {/* Traditional card */}
        <div className="rounded-xl border border-red-100 bg-red-50/10 p-8 dark:border-red-950/20 dark:bg-red-950/5">
          <div className="flex items-center space-x-2 text-red-600">
            <AlertCircle className="h-5 w-5" />
            <h3 className="text-lg font-bold">Traditional Clinical Charting</h3>
          </div>
          <ul className="mt-6 space-y-4 text-sm text-neutral-500 dark:text-neutral-400">
            <li className="flex items-start">
              <span className="mr-2 text-red-500">•</span>
              <span>15+ minutes spent manually transcribing patient symptoms after each consultation.</span>
            </li>
            <li className="flex items-start">
              <span className="mr-2 text-red-500">•</span>
              <span>Higher risk of forgetting secondary symptoms due to administrative backlog.</span>
            </li>
            <li className="flex items-start">
              <span className="mr-2 text-red-500">•</span>
              <span>Administrative fatigue from typing repetitive charts instead of patient care.</span>
            </li>
            <li className="flex items-start">
              <span className="mr-2 text-red-500">•</span>
              <span>Scattered patient history spread across legacy database interfaces.</span>
            </li>
          </ul>
        </div>

        {/* CortexCare card */}
        <div className="rounded-xl border border-emerald-100 bg-emerald-50/10 p-8 dark:border-emerald-950/20 dark:bg-emerald-950/5">
          <div className="flex items-center space-x-2 text-emerald-600">
            <CheckCircle2 className="h-5 w-5" />
            <h3 className="text-lg font-bold">The CortexCare Pipeline</h3>
          </div>
          <ul className="mt-6 space-y-4 text-sm text-neutral-500 dark:text-neutral-400">
            <li className="flex items-start">
              <span className="mr-2 text-emerald-500">•</span>
              <span>100% ambient capture: Audio streams securely via WebRTC during the call.</span>
            </li>
            <li className="flex items-start">
              <span className="mr-2 text-emerald-500">•</span>
              <span>Instant AI Clinical summaries generated by Google Gemini upon session completion.</span>
            </li>
            <li className="flex items-start">
              <span className="mr-2 text-emerald-500">•</span>
              <span>Clinicians spend seconds reviewing and finalising automatically generated notes.</span>
            </li>
            <li className="flex items-start">
              <span className="mr-2 text-emerald-500">•</span>
              <span>Unified chronological timeline logs mapping all patient interactions.</span>
            </li>
          </ul>
        </div>

      </div>
    </section>
  );
};

export default ComparisonSection;
